version: '3.8'
services:
  nginx:
    image: nginx:1.21.4
    volumes:
      - .:/usr/local/www//nginx-ban-ip-access
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/conf.d/localhost.conf:/etc/nginx/conf.d/localhost.conf
      - ./etc/nginx/conf.d/localhost/php.conf:/etc/nginx/conf.d/localhost/php.conf
    ports:
      - ${HTTP_PORT_HTTP:-80}:80

  php:
    image: php:8.0.12-fpm
    volumes:
      - .:/usr/local/www//nginx-ban-ip-access
